import { useState, useEffect } from 'react';
import { FolderOpen, Music, Search, CheckCircle2, AlertCircle, Image as ImageIcon, Loader2, PlayCircle, Edit3 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import * as runtime from '../wailsjs/runtime/runtime';
// Note: These will be generated by Wails
import { GetTracks, SelectDirectory, SearchCovers, ApplyCover, StartAutoTagging, UpdateMetadata } from '../wailsjs/go/main/App';

interface Track {
  filePath: string;
  title: string;
  artist: string;
  album: string;
  hasCover: boolean;
  coverData: string;
  status?: 'idle' | 'searching' | 'processing' | 'done' | 'error';
  year?: string;
  genre?: string;
  comment?: string;
}

interface CoverResult {
  url: string;
  preview: string;
  rank: number;
}

const TrackRow = ({ track, onClick, isBatchProcessing }: { track: Track; onClick: () => void; isBatchProcessing: boolean }) => {
  return (
    <motion.div
      layout
      variants={{
        hidden: { opacity: 0, x: -10 },
        show: { opacity: 1, x: 0 }
      }}
      exit={{ opacity: 0, x: 10 }}
      className={`glass-card rounded-2xl p-3 group hover:bg-white/[0.08] transition-all cursor-pointer relative flex items-center space-x-4
        ${track.status === 'processing' ? 'ring-1 ring-indigo-500/50 bg-white/[0.05]' : ''}`}
      onClick={onClick}
    >
      {/* Cover Image Container */}
      <div className="w-14 h-14 bg-slate-800 rounded-xl flex items-center justify-center shrink-0 overflow-hidden relative border border-white/5 shadow-inner">
        {track.coverData ? (
          <img 
            src={track.coverData} 
            alt={track.title} 
            className="w-full h-full object-cover animate-fadeIn"
          />
        ) : track.hasCover ? (
          <div className="absolute inset-0 bg-emerald-500/20 flex items-center justify-center">
            <CheckCircle2 className="text-emerald-400" size={20} />
          </div>
        ) : (
          <Music className="text-slate-600" size={20} />
        )}
        
        {track.status === 'processing' && (
          <div className="absolute inset-0 bg-black/60 backdrop-blur-[2px] flex items-center justify-center">
            <Loader2 className="animate-spin text-white" size={18} />
          </div>
        )}
      </div>

      {/* Info Column */}
      <div className="flex-1 min-w-0 grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
        <div className="col-span-1 min-w-0">
          <h3 className="font-bold truncate text-[15px] text-white leading-tight">{track.title}</h3>
          <p className="text-[11px] text-slate-500 truncate mt-0.5 font-mono opacity-60">
            {track.filePath.split(/[/\\]/).pop()}
          </p>
        </div>
        <div className="hidden md:block col-span-1">
          <p className="text-sm text-slate-300 truncate flex items-center space-x-2">
            <span className="w-1 h-1 rounded-full bg-slate-600" />
            <span>{track.artist === 'N/A' || !track.artist ? 'Unknown Artist' : track.artist}</span>
          </p>
        </div>
        <div className="hidden lg:block col-span-1">
          <p className="text-xs text-slate-500 truncate italic">
            {track.album === 'N/A' || !track.album ? 'No Album' : track.album}
          </p>
        </div>
      </div>

      {/* Status Icons */}
      <div className="flex items-center space-x-3 pr-2">
        {/* Edit Button */}
        <button
          onClick={(e) => {
            e.stopPropagation();
            onClick(); // Using the same handleSearchCovers for now? No, I should pass a specific edit handler.
          }}
          className="p-2 rounded-full bg-slate-700/50 opacity-0 group-hover:opacity-100 transition-all hover:bg-indigo-500/20"
        >
          <Edit3 size={14} className="text-slate-400 hover:text-indigo-400" />
        </button>

        {track.status === 'done' && (
          <div className="flex items-center text-emerald-400 text-[10px] font-bold uppercase tracking-wider">
            <CheckCircle2 size={14} className="mr-1" />
            Saved
          </div>
        )}
        {track.status === 'error' && <AlertCircle className="text-red-500" size={16} />}
        {!track.hasCover && track.status === 'idle' && (
          <div className="p-2 rounded-full bg-indigo-500/10 opacity-0 group-hover:opacity-100 transition-all">
            <Search size={14} className="text-indigo-400" />
          </div>
        )}
      </div>
    </motion.div>
  );
};

function App() {
  const [directory, setDirectory] = useState<string>('');
  const [tracks, setTracks] = useState<Track[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedTrack, setSelectedTrack] = useState<Track | null>(null);
  const [covers, setCovers] = useState<CoverResult[]>([]);
  const [searchingCovers, setSearchingCovers] = useState(false);
  const [isBatchProcessing, setIsBatchProcessing] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  
  // Metadata Editor State
  const [editingTrack, setEditingTrack] = useState<Track | null>(null);
  const [editForm, setEditForm] = useState({ 
    title: '', 
    artist: '', 
    album: '', 
    year: '', 
    genre: '', 
    comment: '' 
  });
  const [showConfirmDialog, setShowConfirmDialog] = useState(false);

  useEffect(() => {
    // Register Wails Event Listeners
    const offProcessing = runtime.EventsOn("track_processing", (filePath: string) => {
      setTracks(prev => prev.map(t => t.filePath === filePath ? { ...t, status: 'processing' } : t));
    });

    const offUpdated = runtime.EventsOn("track_updated", (meta: any) => {
      setTracks(prev => prev.map(t => 
        t.filePath === meta.filePath 
          ? { ...t, ...meta, status: 'done' } 
          : t
      ));
    });

    const offError = runtime.EventsOn("track_error", (filePath: string) => {
      setTracks(prev => prev.map(t => t.filePath === filePath ? { ...t, status: 'error' } : t));
    });

    const offBatchFinished = runtime.EventsOn("batch_finished", () => {
      setIsBatchProcessing(false);
    });

    return () => {
      // Clean up event listeners
      offProcessing();
      offUpdated();
      offError();
      offBatchFinished();
    };
  }, []);

  const handleSelectDir = async () => {
    try {
      const path = await SelectDirectory();
      if (path) {
        setDirectory(path);
        loadTracks(path);
      }
    } catch (err) {
      console.error(err);
    }
  };

  const loadTracks = async (path: string) => {
    setLoading(true);
    try {
      const data = await GetTracks(path);
      setTracks(data.map((t: any) => ({ ...t, status: 'idle' })));
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSearchCovers = async (track: Track) => {
    if (isBatchProcessing) return;
    setSelectedTrack(track);
    setSearchingCovers(true);
    setCovers([]);
    try {
      const results = await SearchCovers(`${track.artist === 'N/A' ? '' : track.artist} ${track.title}`);
      setCovers(results);
    } catch (err) {
      console.error(err);
    } finally {
      setSearchingCovers(false);
    }
  };

  const handleApplyCover = async (imageURL: string) => {
    if (!selectedTrack) return;
    
    setTracks(prev => prev.map(t => 
      t.filePath === selectedTrack.filePath ? { ...t, status: 'processing' } : t
    ));

    try {
      await ApplyCover(selectedTrack.filePath, imageURL, true);
      setSelectedTrack(null);
    } catch (err) {
      console.error('[UI] ApplyCover error', err);
      setTracks(prev => prev.map(t => 
        t.filePath === selectedTrack.filePath ? { ...t, status: 'error' } : t
      ));
    }
  };

  const handleAutoTagAll = () => {
    const missing = tracks.filter(t => !t.hasCover).map(t => ({
      ...t,
      year: t.year || '',
      genre: t.genre || '',
      comment: t.comment || ''
    }));
    if (missing.length === 0) return;
    
    setIsBatchProcessing(true);
    StartAutoTagging(missing);
  };

  const handleEditMetadata = (track: Track) => {
    setEditingTrack(track);
    setEditForm({
      title: track.title,
      artist: track.artist === 'N/A' || !track.artist ? '' : track.artist,
      album: track.album === 'N/A' || !track.album ? '' : track.album,
      year: track.year || '',
      genre: track.genre || '',
      comment: track.comment || ''
    });
  };

  const handleSaveMetadata = () => {
    if (!editingTrack || !editForm.title.trim()) return;
    setShowConfirmDialog(true);
  };

  const handleConfirmSave = async () => {
    if (!editingTrack) return;
    setShowConfirmDialog(false);
    
    setTracks(prev => prev.map(t => 
      t.filePath === editingTrack.filePath ? { ...t, status: 'processing' } : t
    ));

    try {
      const updated = await UpdateMetadata(
        editingTrack.filePath,
        editForm.title,
        editForm.artist || 'N/A',
        editForm.album || 'N/A',
        editForm.year || '',
        editForm.genre || '',
        editForm.comment || ''
      );
      
      // Update state will happen via event listener "track_updated"
      setEditingTrack(null);
    } catch (err) {
      console.error('Failed to update metadata:', err);
      setTracks(prev => prev.map(t => 
        t.filePath === editingTrack.filePath ? { ...t, status: 'error' } : t
      ));
      alert('Không thể lưu metadata. Vui lòng thử lại.');
    }
  };

  const filteredTracks = tracks.filter(t => 
    t.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    t.artist.toLowerCase().includes(searchQuery.toLowerCase()) ||
    t.album.toLowerCase().includes(searchQuery.toLowerCase()) ||
    t.filePath.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="flex h-screen w-screen text-slate-100 overflow-hidden font-sans">
      {/* Sidebar */}
      <aside className="w-72 glass-card m-4 rounded-3xl flex flex-col p-6 space-y-8">
        <div className="flex items-center space-x-3 px-2">
          <div className="p-2.5 bg-indigo-500 rounded-2xl shadow-xl shadow-indigo-500/40">
            <Music size={24} className="text-white" />
          </div>
          <div>
            <h1 className="font-bold text-xl tracking-tight leading-none">CoverArt</h1>
            <p className="text-[10px] text-indigo-400 font-bold uppercase tracking-widest mt-1">Studio Pro</p>
          </div>
        </div>

        <nav className="flex-1 space-y-3">
          <button 
            onClick={handleSelectDir}
            disabled={isBatchProcessing}
            className="w-full flex items-center space-x-3 px-4 py-3.5 rounded-2xl glass-button text-sm font-medium disabled:opacity-50"
          >
            <FolderOpen size={18} className="text-indigo-400" />
            <span className="truncate">{directory ? 'Change Library' : 'Open Library'}</span>
          </button>

          <button 
            onClick={handleAutoTagAll}
            disabled={isBatchProcessing || tracks.filter(t => !t.hasCover).length === 0}
            className={`w-full flex items-center space-x-3 px-4 py-3.5 rounded-2xl text-sm font-bold transition-all shadow-lg
              ${isBatchProcessing 
                ? 'bg-indigo-500/20 border border-indigo-500/20 text-indigo-300 animate-pulse' 
                : 'bg-indigo-500 hover:bg-indigo-600 text-white shadow-indigo-500/30'}`}
          >
            {isBatchProcessing ? <Loader2 size={18} className="animate-spin" /> : <PlayCircle size={18} />}
            <span>{isBatchProcessing ? 'Processing...' : 'Auto Tag Missing'}</span>
          </button>
        </nav>

        <div className="p-5 bg-white/[0.03] rounded-3xl border border-white/5 space-y-3">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Library Stats</p>
          <div className="space-y-2">
            <div className="flex justify-between items-center text-sm">
              <span className="text-slate-400">Total Tracks</span>
              <span className="font-mono font-bold">{tracks.length}</span>
            </div>
            <div className="flex justify-between items-center text-sm">
              <span className="text-slate-400">Missing Art</span>
              <span className="font-mono font-bold text-indigo-400">{tracks.filter(t => !t.hasCover).length}</span>
            </div>
          </div>
          {tracks.length > 0 && (
            <div className="pt-2">
              <div className="w-full h-1.5 bg-white/5 rounded-full overflow-hidden">
                <motion.div 
                  initial={{ width: 0 }}
                  animate={{ width: `${(tracks.filter(t => t.hasCover).length / tracks.length) * 100}%` }}
                  className="h-full bg-indigo-500" 
                />
              </div>
            </div>
          )}
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 m-4 ml-0 flex flex-col overflow-hidden">
        <header className="p-6 pb-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h2 className="text-4xl font-black tracking-tight">Your Music</h2>
            <div className="flex items-center space-x-2 text-slate-400 text-sm mt-1">
              <FolderOpen size={14} className="text-slate-500" />
              <p className="truncate max-w-sm">{directory || 'Please select a music folder to start'}</p>
            </div>
          </div>

          <div className="relative group max-w-md w-full md:w-80">
            <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
              <Search size={18} className="text-slate-500 group-focus-within:text-indigo-400 transition-colors" />
            </div>
            <input
              type="text"
              placeholder="Search by title, artist, file..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-white/[0.03] border border-white/10 rounded-2xl py-3 pl-11 pr-4 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-all placeholder:text-slate-600"
            />
          </div>
        </header>

        <div className="flex-1 overflow-y-auto no-scrollbar custom-scroll px-6 py-4">
          {loading ? (
            <div className="h-full flex flex-col items-center justify-center space-y-4">
              <div className="relative">
                <div className="absolute inset-0 bg-indigo-500 rounded-full blur-2xl opacity-20 animate-pulse" />
                <Loader2 className="animate-spin text-indigo-500 relative" size={64} />
              </div>
              <p className="text-slate-400 font-medium tracking-wide">Scanning your library...</p>
            </div>
          ) : (
            <div className="space-y-4 max-w-5xl">
              <AnimatePresence mode="popLayout">
                {filteredTracks.map((track) => (
                  <div key={track.filePath} className="relative group">
                    <TrackRow 
                      track={track} 
                      isBatchProcessing={isBatchProcessing}
                      onClick={() => handleSearchCovers(track)} 
                    />
                    {/* Action buttons Overlay - actually integrated into TrackRow now */}
                    <div className="absolute right-4 top-1/2 -translate-y-1/2 flex items-center space-x-2 pointer-events-none group-hover:pointer-events-auto">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleEditMetadata(track);
                        }}
                        className="p-2.5 rounded-xl bg-slate-800 border border-white/10 opacity-0 group-hover:opacity-100 transition-all hover:bg-slate-700 text-slate-400 hover:text-indigo-400 shadow-xl"
                        title="Edit Metadata"
                      >
                        <Edit3 size={16} />
                      </button>
                    </div>
                  </div>
                ))}
              </AnimatePresence>
              
              {tracks.length > 0 && filteredTracks.length === 0 && (
                <div className="h-[60vh] flex flex-col items-center justify-center text-center space-y-4">
                  <div className="w-16 h-16 bg-white/5 rounded-2xl flex items-center justify-center border border-white/5 text-slate-600">
                    <Search size={24} />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold">No results for "{searchQuery}"</h3>
                    <p className="text-sm text-slate-500">Try a different keyword or clear search</p>
                  </div>
                  <button 
                    onClick={() => setSearchQuery('')}
                    className="text-indigo-400 text-sm font-bold hover:text-indigo-300 transition-colors"
                  >
                    Clear search
                  </button>
                </div>
              )}

              {tracks.length === 0 && !loading && (
                <div className="h-[70vh] flex flex-col items-center justify-center space-y-8">
                  <motion.div 
                    initial={{ scale: 0.9, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    className="relative"
                  >
                    <div className="absolute -inset-4 bg-indigo-500/20 rounded-[3rem] blur-2xl animate-pulse" />
                    <div className="w-24 h-24 bg-slate-800 rounded-[2.5rem] flex items-center justify-center border border-white/5 shadow-2xl relative">
                      <Music size={40} className="text-indigo-500" />
                    </div>
                  </motion.div>
                  <div className="text-center space-y-2 max-w-sm">
                    <h3 className="text-2xl font-black tracking-tight">Your library is ready</h3>
                    <p className="text-slate-400 text-sm">
                      {directory 
                        ? "No supported audio files (.mp3, .flac) found in this directory." 
                        : "Select a folder containing your music collection to start hunting for amazing cover arts."}
                    </p>
                  </div>
                  {!directory && (
                    <button 
                      onClick={handleSelectDir}
                      className="px-8 py-3.5 bg-indigo-500 hover:bg-indigo-600 text-white rounded-2xl font-black shadow-xl shadow-indigo-500/30 transition-all flex items-center space-x-2"
                    >
                      <FolderOpen size={18} />
                      <span>OPEN LIBRARY</span>
                    </button>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      </main>

      {/* Cover Picker Modal */}
      <AnimatePresence>
        {selectedTrack && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-8"
            onClick={() => setSelectedTrack(null)}
          >
            <motion.div 
              initial={{ scale: 0.95, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.95, opacity: 0, y: 20 }}
              className="glass-card w-full max-w-3xl rounded-[2.5rem] p-10 flex flex-col space-y-8 max-h-[85vh] relative overflow-hidden"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="absolute top-0 right-0 p-8">
                <button 
                  onClick={() => setSelectedTrack(null)} 
                  className="w-10 h-10 rounded-full glass-button flex items-center justify-center text-slate-400 hover:text-white transition-all"
                >
                  ✕
                </button>
              </div>

              <div className="flex items-center space-x-6">
                <div className="w-20 h-20 bg-indigo-500/10 rounded-3xl flex items-center justify-center shrink-0 border border-indigo-500/20 shadow-inner">
                  {selectedTrack.coverData ? (
                    <img src={selectedTrack.coverData} alt="Current" className="w-full h-full object-cover rounded-3xl" />
                  ) : (
                    <Music size={32} className="text-indigo-400" />
                  )}
                </div>
                <div>
                  <h3 className="text-2xl font-black tracking-tight">{selectedTrack.title}</h3>
                  <p className="text-slate-400 font-medium">{selectedTrack.artist} — {selectedTrack.album}</p>
                </div>
              </div>

              <div className="flex-1 overflow-y-auto custom-scroll pr-4 -mr-4">
                {searchingCovers ? (
                  <div className="h-64 flex flex-col items-center justify-center space-y-6">
                    <div className="relative">
                      <div className="absolute inset-0 bg-indigo-500 rounded-full blur-xl opacity-20 animate-pulse" />
                      <Loader2 className="animate-spin text-indigo-500 relative" size={48} />
                    </div>
                    <p className="text-slate-400 font-medium animate-pulse">Hunting for the perfect cover art...</p>
                  </div>
                ) : (
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-6">
                    {covers.map((cover, idx) => (
                      <motion.div
                        key={idx}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0, transition: { delay: idx * 0.05 } }}
                        whileHover={{ y: -4 }}
                        onClick={() => handleApplyCover(cover.url)}
                        className="aspect-square bg-slate-800 rounded-3xl overflow-hidden cursor-pointer border border-white/5 hover:border-indigo-500 transition-all group relative shadow-2xl"
                      >
                        <img src={cover.preview} alt={`Result ${idx}`} className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" />
                        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-0 group-hover:opacity-100 flex flex-col items-center justify-end pb-6 transition-all">
                          <span className="px-5 py-2.5 bg-indigo-500 text-white rounded-2xl text-xs font-black shadow-xl shadow-indigo-500/40 transform translate-y-2 group-hover:translate-y-0 transition-transform">
                            APPLY ART
                          </span>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                )}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Metadata Editor Modal */}
      <AnimatePresence>
        {editingTrack && !showConfirmDialog && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-8"
            onClick={() => setEditingTrack(null)}
          >
            <motion.div 
              initial={{ scale: 0.95, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.95, opacity: 0, y: 20 }}
              className="glass-card w-full max-w-lg rounded-3xl p-8 flex flex-col space-y-6 max-h-[90vh] overflow-hidden"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between border-b border-white/5 pb-4">
                <div className="flex items-center space-x-3">
                  <div className="p-2 bg-indigo-500/20 rounded-xl">
                    <Edit3 size={20} className="text-indigo-400" />
                  </div>
                  <h3 className="text-xl font-black tracking-tight">Edit Metadata</h3>
                </div>
                <button 
                  onClick={() => setEditingTrack(null)} 
                  className="w-8 h-8 rounded-full glass-button flex items-center justify-center text-slate-400 hover:text-white transition-all"
                >
                  ✕
                </button>
              </div>

              <div className="flex-1 overflow-y-auto no-scrollbar pr-2 space-y-5">
                {/* Title - Required */}
                <div className="space-y-2">
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1">
                    Title <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={editForm.title}
                    onChange={(e) => setEditForm({ ...editForm, title: e.target.value })}
                    className="w-full bg-white/[0.03] border border-white/10 rounded-2xl py-3 px-5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-all placeholder:text-slate-700"
                    placeholder="Song Title"
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  {/* Artist */}
                  <div className="space-y-2">
                    <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1">Artist</label>
                    <input
                      type="text"
                      value={editForm.artist}
                      onChange={(e) => setEditForm({ ...editForm, artist: e.target.value })}
                      className="w-full bg-white/[0.03] border border-white/10 rounded-2xl py-3 px-5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-all placeholder:text-slate-700"
                      placeholder="Artist Name"
                    />
                  </div>
                  {/* Album */}
                  <div className="space-y-2">
                    <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1">Album</label>
                    <input
                      type="text"
                      value={editForm.album}
                      onChange={(e) => setEditForm({ ...editForm, album: e.target.value })}
                      className="w-full bg-white/[0.03] border border-white/10 rounded-2xl py-3 px-5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-all placeholder:text-slate-700"
                      placeholder="Album Name"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  {/* Year */}
                  <div className="space-y-2">
                    <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1">Year</label>
                    <input
                      type="text"
                      value={editForm.year}
                      onChange={(e) => setEditForm({ ...editForm, year: e.target.value })}
                      className="w-full bg-white/[0.03] border border-white/10 rounded-2xl py-3 px-5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-all placeholder:text-slate-700"
                      placeholder="e.g. 2024"
                    />
                  </div>
                  {/* Genre */}
                  <div className="space-y-2">
                    <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1">Genre</label>
                    <input
                      type="text"
                      value={editForm.genre}
                      onChange={(e) => setEditForm({ ...editForm, genre: e.target.value })}
                      className="w-full bg-white/[0.03] border border-white/10 rounded-2xl py-3 px-5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-all placeholder:text-slate-700"
                      placeholder="e.g. Pop"
                    />
                  </div>
                </div>

                {/* Comment */}
                <div className="space-y-2">
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1">Comment</label>
                  <textarea
                    value={editForm.comment}
                    onChange={(e) => setEditForm({ ...editForm, comment: e.target.value })}
                    rows={3}
                    className="w-full bg-white/[0.03] border border-white/10 rounded-2xl py-3 px-5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-all resize-none placeholder:text-slate-700"
                    placeholder="Additional notes..."
                  />
                </div>
              </div>

              <div className="flex space-x-3 pt-4 border-t border-white/5">
                <button
                  onClick={() => setEditingTrack(null)}
                  className="flex-1 px-4 py-4 rounded-2xl glass-button text-sm font-bold hover:bg-white/[0.08] transition-all"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSaveMetadata}
                  disabled={!editForm.title.trim()}
                  className="flex-1 px-4 py-4 bg-indigo-500 hover:bg-indigo-600 disabled:opacity-30 disabled:cursor-not-allowed text-white rounded-2xl text-sm font-black shadow-xl shadow-indigo-500/30 transition-all"
                >
                  Save Changes
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Confirmation Dialog */}
      <AnimatePresence>
        {showConfirmDialog && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[60] flex items-center justify-center bg-black/90 backdrop-blur-sm"
          >
            <motion.div 
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="glass-card w-full max-w-sm rounded-[2rem] p-8 text-center space-y-6"
            >
              <div className="w-16 h-16 bg-yellow-500/10 rounded-full flex items-center justify-center mx-auto border border-yellow-500/20">
                <AlertCircle className="text-yellow-400" size={32} />
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-black tracking-tight">Lưu thay đổi?</h3>
                <p className="text-sm text-slate-400 px-4">Thông tin sẽ được ghi trực tiếp vào tệp nhạc. Thao tác này không thể hoàn tác.</p>
              </div>
              <div className="flex flex-col space-y-3">
                <button
                  onClick={handleConfirmSave}
                  className="w-full py-4 bg-indigo-500 hover:bg-indigo-600 text-white rounded-2xl font-black text-sm transition-all"
                >
                  Dồng ý, Lưu ngay
                </button>
                <button
                  onClick={() => setShowConfirmDialog(false)}
                  className="w-full py-3 text-slate-500 hover:text-slate-300 font-bold text-xs uppercase tracking-widest transition-all"
                >
                  Bỏ qua
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default App;
