// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ApplyCover(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GetTracks(arg1:string):Promise<Array<backend.TrackMetadata>>;

export function Greet(arg1:string):Promise<string>;

export function SearchCovers(arg1:string):Promise<Array<backend.CoverResult>>;

export function SelectDirectory():Promise<string>;

export function StartAutoTagging(arg1:Array<backend.TrackMetadata>):Promise<void>;

export function UpdateMetadata(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<backend.TrackMetadata>;
