// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyCover(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyCover'](arg1, arg2, arg3);
}

export function GetTracks(arg1) {
  return window['go']['main']['App']['GetTracks'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchCovers(arg1) {
  return window['go']['main']['App']['SearchCovers'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartAutoTagging(arg1) {
  return window['go']['main']['App']['StartAutoTagging'](arg1);
}

export function UpdateMetadata(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateMetadata'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
